services:
  # Backend API
  backend:
    build: ./backend
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ap-south-1
      S3_BUCKET: ti-hackathons-2025
    expose:
      - "8000"
    restart: always

  # Backend Load Balancer
  backend-lb:
    image: nginx:alpine
    container_name: backend-lb
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: always

  # Frontend React + Nginx
  frontend:
    build: ./frontend
    container_name: s3-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-lb
    restart: always
