FROM node:20-alpine as build
WORKDIR /app
COPY web/package.json ./
RUN npm install
COPY web/. ./
RUN npm run build

FROM node:20-alpine
RUN npm i -g serve
WORKDIR /site
COPY --from=build /app/dist ./
EXPOSE 5173
CMD ["serve","-s",".","-l","5173"]
