version: "3.9"

services:
  # Load balancer for Express API
  nginx:
    image: nginx:alpine
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3

  # 3 replicas of your backend
  server1:
    build:
      context: .
      dockerfile: root/Dockerfile.server
    env_file:
      - server/.env
    restart: unless-stopped

  server2:
    build:
      context: .
      dockerfile: root/Dockerfile.server
    env_file:
      - server/.env
    restart: unless-stopped

  server3:
    build:
      context: .
      dockerfile: root/Dockerfile.server
    env_file:
      - server/.env
    restart: unless-stopped
