version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: root/Dockerfile.server
    env_file:
      - server/.env
    ports:
      - "4000:4000"
    volumes:
      - ~/.aws:/root/.aws:ro
    profiles: ["prod"]
    command: npm run start  # production start script
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  web:
    build:
      context: .
      dockerfile: root/Dockerfile.web
    env_file:
      - web/.env
    ports:
      - "80:5173"   # expose on port 80 for production
    depends_on:
      - server
    profiles: ["prod"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 5s
      retries: 3
